// =====================================================================
// questions.js — the written question bank + unit list.
// To add a question, copy one { ... } block and change the words.
//   type: "mc"    = multiple choice  (choices + answer)
//         "order" = put in order     (items listed in the CORRECT order)
//         "type"  = type the answer  (answer = list of accepted answers)
// =====================================================================

const UNITS = [
  { id: 1, name: 'Notation Basics', icon: '𝄞', blurb: 'Staff & clefs, pitch, octaves, accidentals, enharmonics' },
  { id: 2, name: 'Rhythm',          icon: '♪', blurb: 'Durations, ties, dots, division & subdivision' },
  { id: 3, name: 'Meter',           icon: '𝄴', blurb: 'Simple, compound & asymmetrical meter' },
  { id: 4, name: 'Expression',      icon: '𝆑', blurb: 'Dynamics, tempo markings, tempo changes' },
  { id: 5, name: 'Major Scales & Keys', icon: '♯', blurb: 'Major scales, scale degrees, major key signatures' },
  { id: 6, name: 'Minor Scales & Keys', icon: '♭', blurb: 'Natural, harmonic, melodic minor; relative & parallel' },
  { id: 7, name: 'Key Relationships',   icon: '♮', blurb: 'Circle of fifths, closely related keys, pentatonic, chromatic, modes' },
];

const WRITTEN = [
  // ---------------- UNIT 1: Notation basics ----------------
  { unit: 1, tag: 'clefs', type: 'mc', prompt: 'The treble clef is also called the…', choices: ['G clef', 'F clef', 'C clef', 'Alto clef'], answer: 'G clef', explain: 'Its curl wraps around the G line (2nd line from the bottom).' },
  { unit: 1, tag: 'clefs', type: 'mc', prompt: 'The bass clef is also called the…', choices: ['F clef', 'G clef', 'C clef', 'Tenor clef'], answer: 'F clef', explain: 'Its two dots surround the F line (4th line from the bottom).' },
  { unit: 1, tag: 'clefs', type: 'mc', prompt: 'In alto clef, the middle line is…', choices: ['Middle C (C4)', 'G4', 'F3', 'B4'], answer: 'Middle C (C4)', explain: 'Alto clef is a C clef: its center points to middle C on the middle line.' },
  { unit: 1, tag: 'octaves', type: 'mc', prompt: 'Middle C is written in octave notation as…', choices: ['C4', 'C3', 'C5', 'C0'], answer: 'C4', explain: 'Octave numbers change at C. Middle C = C4; the B just below it is B3.' },
  { unit: 1, tag: 'octaves', type: 'mc', prompt: 'Two notes an octave apart share the same…', choices: ['Letter name', 'Frequency', 'Line or space', 'Duration'], answer: 'Letter name', explain: 'Octave equivalence: notes an octave apart sound "the same" and share a letter name (the upper one vibrates twice as fast).' },
  { unit: 1, tag: 'octaves', type: 'mc', prompt: 'What is the note one half step below C4?', choices: ['B3', 'B4', 'C♭5', 'D3'], answer: 'B3', explain: 'The octave number changes at C, so the B just below middle C is B3.' },
  { unit: 1, tag: 'accidentals', type: 'mc', prompt: 'A natural sign (♮)…', choices: ['Cancels a previous sharp or flat', 'Raises a note a half step', 'Lowers a note a half step', 'Raises a note a whole step'], answer: 'Cancels a previous sharp or flat', explain: 'A natural returns the note to its unaltered letter pitch.' },
  { unit: 1, tag: 'accidentals', type: 'mc', prompt: 'An accidental in a measure lasts…', choices: ['Until the barline', 'For one note only', 'For the whole piece', 'Until the next rest'], answer: 'Until the barline', explain: 'It applies to that pitch for the rest of the measure, then the barline cancels it.' },
  { unit: 1, tag: 'accidentals', type: 'mc', prompt: 'Which pairs of white keys are only a half step apart?', choices: ['E–F and B–C', 'C–D and F–G', 'A–B and D–E', 'G–A and C–D'], answer: 'E–F and B–C', explain: 'There is no black key between E–F or B–C.' },
  { unit: 1, tag: 'enharmonics', type: 'mc', prompt: 'Which note is enharmonic to C♯?', choices: ['D♭', 'D♯', 'B♭', 'C♭'], answer: 'D♭', explain: 'Enharmonic = same key on the piano, different spelling.' },
  { unit: 1, tag: 'enharmonics', type: 'mc', prompt: 'Which note is enharmonic to E♯?', choices: ['F', 'F♯', 'E♭', 'D♯'], answer: 'F', explain: 'E and F are a half step apart, so E♯ = F.' },
  { unit: 1, tag: 'enharmonics', type: 'mc', prompt: 'Which note is enharmonic to C♭?', choices: ['B', 'B♭', 'C♯', 'D♭'], answer: 'B', explain: 'B and C are a half step apart, so C♭ = B.' },
  { unit: 1, tag: 'enharmonics', type: 'mc', prompt: 'Which note is enharmonic to G♭?', choices: ['F♯', 'G♯', 'A♭', 'F'], answer: 'F♯', explain: 'F♯ and G♭ are the same black key.' },

  // ---------------- UNIT 2: Rhythm ----------------
  { unit: 2, tag: 'durations', type: 'mc', prompt: 'How many quarter notes equal one whole note?', choices: ['4', '2', '3', '8'], answer: '4', explain: 'Whole = 2 halves = 4 quarters = 8 eighths = 16 sixteenths.' },
  { unit: 2, tag: 'durations', type: 'mc', prompt: 'How many eighth notes equal one half note?', choices: ['4', '2', '8', '3'], answer: '4', explain: 'A half note = 2 quarters = 4 eighths.' },
  { unit: 2, tag: 'durations', type: 'mc', prompt: 'How many sixteenth notes fit in one quarter note?', choices: ['4', '2', '8', '16'], answer: '4', explain: 'Quarter → 2 eighths → 4 sixteenths.' },
  { unit: 2, tag: 'dots', type: 'mc', prompt: 'A dot after a note adds…', choices: ['Half of the note\'s value', 'One beat', 'The same value again', 'A quarter of the note\'s value'], answer: 'Half of the note\'s value', explain: 'Dotted half = half + quarter = 3 quarter-note beats.' },
  { unit: 2, tag: 'dots', type: 'mc', prompt: 'In 4/4, a dotted half note lasts how many beats?', choices: ['3', '2', '2½', '4'], answer: '3', explain: '2 beats + half of 2 (1 beat) = 3.' },
  { unit: 2, tag: 'dots', type: 'mc', prompt: 'A dotted quarter note equals…', choices: ['3 eighth notes', '2 eighth notes', '4 sixteenth notes', '1 half note'], answer: '3 eighth notes', explain: 'Quarter (2 eighths) + dot (1 eighth) = 3 eighths.' },
  { unit: 2, tag: 'dots', type: 'mc', prompt: 'A double-dotted half note equals how many quarter-note beats?', choices: ['3½', '3', '4', '2¾'], answer: '3½', explain: '2 + 1 (first dot) + ½ (second dot = half of the first dot) = 3½.' },
  { unit: 2, tag: 'ties', type: 'mc', prompt: 'A tie connects…', choices: ['Two notes of the same pitch into one longer sound', 'Notes of different pitches smoothly', 'Two measures of rest', 'A note to a dot'], answer: 'Two notes of the same pitch into one longer sound', explain: 'Tied notes are played once and held for the combined value. Different pitches = a slur.' },
  { unit: 2, tag: 'ties', type: 'mc', prompt: 'A half note tied to a quarter note lasts…', choices: ['3 beats', '2 beats', '1½ beats', '4 beats'], answer: '3 beats', explain: '2 + 1 = 3 beats (in a quarter-note meter).' },
  { unit: 2, tag: 'division', type: 'mc', prompt: 'Dividing a beat into three equal parts in simple meter is called a…', choices: ['Triplet', 'Duplet', 'Syncopation', 'Tie'], answer: 'Triplet', explain: 'Simple meter divides the beat in 2; a triplet borrows a 3-way division.' },
  { unit: 2, tag: 'division', type: 'mc', prompt: 'In simple meter, the beat naturally divides into…', choices: ['2 parts', '3 parts', '4 parts', '6 parts'], answer: '2 parts', explain: 'Simple = beat divides in 2 (subdivides in 4). Compound = divides in 3 (subdivides in 6).' },
  { unit: 2, tag: 'division', type: 'mc', prompt: 'In compound meter, the beat subdivides into…', choices: ['6 parts', '4 parts', '3 parts', '2 parts'], answer: '6 parts', explain: 'Compound: division = 3, subdivision = 6.' },

  // ---------------- UNIT 3: Meter ----------------
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: 'Classify 3/4.', choices: ['Simple triple', 'Compound triple', 'Simple duple', 'Compound duple'], answer: 'Simple triple', explain: '3 beats, each a quarter note that divides into 2.' },
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: 'Classify 6/8.', choices: ['Compound duple', 'Simple triple', 'Compound triple', 'Simple duple'], answer: 'Compound duple', explain: 'Top number 6 → compound; 6 ÷ 3 = 2 beats (dotted quarters).' },
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: 'Classify 9/8.', choices: ['Compound triple', 'Simple triple', 'Compound quadruple', 'Asymmetrical'], answer: 'Compound triple', explain: '9 ÷ 3 = 3 dotted-quarter beats.' },
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: 'Classify 12/8.', choices: ['Compound quadruple', 'Simple quadruple', 'Compound triple', 'Asymmetrical'], answer: 'Compound quadruple', explain: '12 ÷ 3 = 4 dotted-quarter beats.' },
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: 'Classify 2/2 (cut time).', choices: ['Simple duple', 'Compound duple', 'Simple quadruple', 'Asymmetrical'], answer: 'Simple duple', explain: '2 half-note beats, each dividing into 2 quarters.' },
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: 'Which time signature is asymmetrical?', choices: ['7/8', '6/8', '3/4', '12/8'], answer: '7/8', explain: 'Asymmetrical meters mix groups of 2 and 3 (7/8 = 2+2+3, 3+2+2, etc.).' },
  { unit: 3, tag: 'meter-type', type: 'mc', prompt: '5/8 is usually grouped as…', choices: ['2+3 or 3+2', '2+2+1', '5 equal beats', '4+1'], answer: '2+3 or 3+2', explain: 'Asymmetrical meters have unequal beats made of 2s and 3s.' },
  { unit: 3, tag: 'beat-unit', type: 'mc', prompt: 'In 6/8, what note gets one beat?', choices: ['Dotted quarter', 'Eighth', 'Quarter', 'Dotted half'], answer: 'Dotted quarter', explain: 'In compound meter the beat is a dotted note (here, three eighths).' },
  { unit: 3, tag: 'beat-unit', type: 'mc', prompt: 'In 3/2, what note gets one beat?', choices: ['Half note', 'Quarter note', 'Dotted half', 'Whole note'], answer: 'Half note', explain: 'Simple meter: the bottom number names the beat (2 = half note).' },
  { unit: 3, tag: 'conversion', type: 'mc', prompt: 'Which compound meter matches 2/4 (same number of beats)?', choices: ['6/8', '9/8', '12/8', '3/8'], answer: '6/8', explain: 'Worksheet 3: 2 quarter beats ↔ 2 dotted-quarter beats. Twinkle, Twinkle moves from 2/4 to 6/8.' },
  { unit: 3, tag: 'conversion', type: 'mc', prompt: 'Which compound meter matches 3/4?', choices: ['9/8', '6/8', '12/8', '3/8'], answer: '9/8', explain: 'Worksheet 3: We Three Kings moves from 3/4 to 9/8 — 3 beats each.' },
  { unit: 3, tag: 'conversion', type: 'mc', prompt: 'Which compound meter matches 4/4?', choices: ['12/8', '6/8', '9/8', '4/8'], answer: '12/8', explain: 'Worksheet 3: London Bridge moves from 4/4 to 12/8 — 4 beats each.' },
  { unit: 3, tag: 'conversion', type: 'mc', prompt: 'Moving from 4/4 to 12/8, a quarter note becomes a…', choices: ['Dotted quarter', 'Eighth', 'Dotted half', 'Quarter'], answer: 'Dotted quarter', explain: 'Each 1-beat note becomes the compound 1-beat note: the dotted quarter.' },
  { unit: 3, tag: 'conversion', type: 'mc', prompt: 'Moving from 4/4 to 12/8, a half note becomes a…', choices: ['Dotted half', 'Half', 'Dotted quarter', 'Whole'], answer: 'Dotted half', explain: '2 beats in simple → 2 dotted-quarter beats = a dotted half.' },
  { unit: 3, tag: 'conversion', type: 'mc', prompt: 'Moving from 2/4 to 6/8, two eighth notes (one beat) become…', choices: ['Three eighth notes', 'Two eighth notes', 'One quarter', 'Four sixteenths'], answer: 'Three eighth notes', explain: 'One simple beat (2 eighths) → one compound beat (3 eighths).' },

  // ---------------- UNIT 4: Expression (tempo sheet + dynamics) ----------------
  { unit: 4, tag: 'dynamics', type: 'order', prompt: 'Put these dynamics in order from softest to loudest.', items: ['pp', 'p', 'mp', 'mf', 'f', 'ff'], explain: 'pianissimo → piano → mezzo piano → mezzo forte → forte → fortissimo.' },
  { unit: 4, tag: 'dynamics', type: 'mc', prompt: 'What does "mf" mean?', choices: ['Moderately loud', 'Moderately soft', 'Very loud', 'Gradually louder'], answer: 'Moderately loud', explain: 'mezzo forte = moderately loud.' },
  { unit: 4, tag: 'dynamics', type: 'mc', prompt: 'A crescendo means…', choices: ['Gradually get louder', 'Gradually get softer', 'Suddenly loud', 'Gradually slow down'], answer: 'Gradually get louder', explain: 'Crescendo (<) = louder; decrescendo / diminuendo (>) = softer.' },
  { unit: 4, tag: 'dynamics', type: 'mc', prompt: '"sfz" (sforzando) means…', choices: ['A sudden strong accent', 'Very soft', 'Gradually softer', 'Hold the note'], answer: 'A sudden strong accent', explain: 'Sforzando = a sudden, forceful accent on one note.' },
  { unit: 4, tag: 'tempo', type: 'order', prompt: 'Put these tempo markings in order from slowest to fastest.', items: ['Grave', 'Largo', 'Adagio', 'Andante', 'Moderato', 'Allegro', 'Presto'], explain: 'From the tempo sheet: Grave 25–45, Largo 40–60, Adagio 66–76, Andante 76–108, Moderato 108–120, Allegro 120–168, Presto 168–200 bpm.' },
  { unit: 4, tag: 'tempo', type: 'order', prompt: 'Order slowest to fastest.', items: ['Larghissimo', 'Lento', 'Larghetto', 'Andantino', 'Allegretto', 'Vivace', 'Prestissimo'], explain: 'Larghissimo ≤24, Lento 45–60, Larghetto 60–66, Andantino 80–108, Allegretto 112–120, Vivace 168–176, Prestissimo 200+ bpm.' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: '"Andante" means…', choices: ['At a walking pace', 'Fast and bright', 'Very slow', 'Lively and fast'], answer: 'At a walking pace', explain: 'Andante = walking pace, 76–108 bpm.' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: '"Adagio" literally means…', choices: ['At ease (slow and stately)', 'At a walking pace', 'Broadly', 'Lively'], answer: 'At ease (slow and stately)', explain: 'Adagio = slow and stately, 66–76 bpm.' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: 'Which tempo is fastest?', choices: ['Prestissimo', 'Presto', 'Vivace', 'Allegro'], answer: 'Prestissimo', explain: 'Prestissimo = 200+ bpm, even faster than Presto.' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: 'Allegro is about…', choices: ['120–168 bpm', '66–76 bpm', '76–108 bpm', '200+ bpm'], answer: '120–168 bpm', explain: 'Allegro = fast, quickly, and bright: 120–168 bpm.' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: 'Which is the slowest?', choices: ['Grave', 'Lento', 'Adagio', 'Larghetto'], answer: 'Grave', explain: 'Grave (25–45) < Lento (45–60) < Larghetto (60–66) < Adagio (66–76).' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: 'Adding "-issimo" to a tempo word…', choices: ['Amplifies it', 'Diminishes it', 'Reverses it', 'Means gradually'], answer: 'Amplifies it', explain: 'Presto → Prestissimo (even faster). "-ino" / "-etto" diminish (Allegro → Allegretto).' },
  { unit: 4, tag: 'tempo', type: 'mc', prompt: 'Compared to Allegro, Allegretto is…', choices: ['A little slower', 'A little faster', 'Much faster', 'The same'], answer: 'A little slower', explain: '"-etto" diminishes: Allegretto (112–120) is moderately fast.' },
  { unit: 4, tag: 'tempo-change', type: 'mc', prompt: '"Ritenuto" means…', choices: ['Immediately slow down', 'Gradually slow down', 'Gradually speed up', 'Return to the original tempo'], answer: 'Immediately slow down', explain: 'Ritenuto = immediate; ritardando and rallentando = gradual.' },
  { unit: 4, tag: 'tempo-change', type: 'mc', prompt: '"Accelerando" means…', choices: ['Gradually speed up (quickly)', 'Immediately speed up', 'Gradually slow down', 'Gradually louder'], answer: 'Gradually speed up (quickly)', explain: 'Accelerando speeds up quickly; stringendo speeds up slowly.' },
  { unit: 4, tag: 'tempo-change', type: 'mc', prompt: 'Which slows down MORE: rallentando or ritardando?', choices: ['Rallentando', 'Ritardando', 'They are identical', 'Neither slows down'], answer: 'Rallentando', explain: 'Per the tempo sheet, ritardando slows "but not as much as rallentando."' },
  { unit: 4, tag: 'tempo-change', type: 'mc', prompt: '"Stringendo" means…', choices: ['Gradually speeding up (slowly)', 'Immediately slowing down', 'Getting softer', 'Very fast'], answer: 'Gradually speeding up (slowly)', explain: 'Stringendo = pressing forward gradually.' },

  // ---------------- UNIT 5: Major ----------------
  { unit: 5, tag: 'major-scales', type: 'mc', prompt: 'The pattern of whole (W) and half (H) steps in a major scale is…', choices: ['W W H W W W H', 'W H W W H W W', 'W W W H W W H', 'H W W W H W W'], answer: 'W W H W W W H', explain: 'Half steps fall between degrees 3–4 and 7–8.' },
  { unit: 5, tag: 'major-scales', type: 'mc', prompt: 'In a major scale, half steps occur between degrees…', choices: ['3–4 and 7–8', '2–3 and 5–6', '3–4 and 6–7', '4–5 and 7–8'], answer: '3–4 and 7–8', explain: 'W W H W W W H.' },
  { unit: 5, tag: 'scale-degrees', type: 'mc', prompt: 'Scale degree 5 is called the…', choices: ['Dominant', 'Subdominant', 'Mediant', 'Submediant'], answer: 'Dominant', explain: '1 tonic, 2 supertonic, 3 mediant, 4 subdominant, 5 dominant, 6 submediant, 7 leading tone.' },
  { unit: 5, tag: 'scale-degrees', type: 'mc', prompt: 'Which scale degree is the submediant?', choices: ['6', '4', '3', '2'], answer: '6', explain: 'Submediant = 6, halfway between the tonic and the subdominant below.' },
  { unit: 5, tag: 'scale-degrees', type: 'mc', prompt: 'The leading tone is how far below the tonic?', choices: ['A half step', 'A whole step', 'A minor third', 'An octave'], answer: 'A half step', explain: 'It "leads" up to the tonic by half step. A whole step below = subtonic.' },
  { unit: 5, tag: 'key-signatures', type: 'mc', prompt: 'The order of sharps is…', choices: ['F C G D A E B', 'B E A D G C F', 'C G D A E B F', 'F B E A D G C'], answer: 'F C G D A E B', explain: '"Father Charles Goes Down And Ends Battle." Flats are the reverse: B E A D G C F.' },
  { unit: 5, tag: 'key-signatures', type: 'mc', prompt: 'Shortcut for sharp keys: the major key is…', choices: ['A half step above the last sharp', 'The last sharp', 'A whole step above the last sharp', 'The first sharp'], answer: 'A half step above the last sharp', explain: 'Last sharp C♯ → D major. For flat keys, the next-to-last flat is the key.' },
  { unit: 5, tag: 'key-signatures', type: 'mc', prompt: 'Shortcut for flat keys: the major key is…', choices: ['The second-to-last flat', 'The last flat', 'A half step above the last flat', 'The first flat'], answer: 'The second-to-last flat', explain: 'B♭ E♭ A♭ → second-to-last = E♭ major. (F major, with one flat, you memorize.)' },

  // ---------------- UNIT 6: Minor (HW 2) ----------------
  { unit: 6, tag: 'minor-scales', type: 'mc', prompt: 'The harmonic minor scale raises which degree of natural minor?', choices: ['7', '6', '3', '6 and 7'], answer: '7', explain: 'Raising 7 creates a leading tone (and an augmented 2nd between 6 and 7).' },
  { unit: 6, tag: 'minor-scales', type: 'mc', prompt: 'Ascending melodic minor raises which degrees of natural minor?', choices: ['6 and 7', '7 only', '3 and 6', '6 only'], answer: '6 and 7', explain: 'Ascending: raise 6 and 7. Descending: return to natural minor.' },
  { unit: 6, tag: 'minor-scales', type: 'mc', prompt: 'Descending melodic minor is the same as…', choices: ['Natural minor', 'Harmonic minor', 'Major', 'Ascending melodic minor'], answer: 'Natural minor', explain: 'The raised 6 and 7 are lowered again going down.' },
  { unit: 6, tag: 'minor-scales', type: 'mc', prompt: 'The step pattern of natural minor is…', choices: ['W H W W H W W', 'W W H W W W H', 'W H W W H +2 H', 'W W H W W H W'], answer: 'W H W W H W W', explain: 'Half steps between 2–3 and 5–6.' },
  { unit: 6, tag: 'scale-degrees', type: 'mc', prompt: 'In natural minor, scale degree 7 is called the…', choices: ['Subtonic', 'Leading tone', 'Submediant', 'Supertonic'], answer: 'Subtonic', explain: 'A whole step below the tonic = subtonic. Raised a half step (harmonic minor) = leading tone.' },
  { unit: 6, tag: 'scale-degrees', type: 'mc', prompt: 'HW 2: In C minor, the mediant is…', choices: ['E♭', 'E', 'D', 'A♭'], answer: 'E♭', explain: 'C minor: C D E♭ F G A♭ B♭. Mediant = 3rd degree = E♭.' },
  { unit: 6, tag: 'scale-degrees', type: 'mc', prompt: 'HW 2: In F minor, the subtonic is…', choices: ['E♭', 'E', 'D♭', 'B♭'], answer: 'E♭', explain: 'F minor: F G A♭ B♭ C D♭ E♭. Subtonic = lowered 7th = E♭.' },
  { unit: 6, tag: 'scale-degrees', type: 'mc', prompt: 'HW 2: In F♯ minor, the subdominant is…', choices: ['B', 'C♯', 'A', 'D'], answer: 'B', explain: 'F♯ minor: F♯ G♯ A B C♯ D E. Subdominant = 4th = B.' },
  { unit: 6, tag: 'scale-degrees', type: 'mc', prompt: 'HW 2: In G minor, the supertonic is…', choices: ['A', 'B♭', 'F', 'A♭'], answer: 'A', explain: 'G minor: G A B♭ C D E♭ F. Supertonic = 2nd = A.' },
  { unit: 6, tag: 'relative-parallel', type: 'mc', prompt: 'Relative major and minor keys share the same…', choices: ['Key signature', 'Tonic', 'Leading tone', 'Dominant'], answer: 'Key signature', explain: 'C major and A minor both have no sharps or flats. Parallel keys share the same tonic.' },
  { unit: 6, tag: 'relative-parallel', type: 'mc', prompt: 'Parallel major and minor keys share the same…', choices: ['Tonic', 'Key signature', 'Relative minor', 'Number of sharps'], answer: 'Tonic', explain: 'C major and C minor are parallel: same tonic, different signatures (0 vs 3 flats).' },
  { unit: 6, tag: 'relative-parallel', type: 'mc', prompt: 'To find the relative minor of a major key, go…', choices: ['Down a minor 3rd (3 half steps)', 'Up a minor 3rd', 'Down a perfect 5th', 'Up a whole step'], answer: 'Down a minor 3rd (3 half steps)', explain: 'It\'s scale degree 6 of the major key. C major → A minor.' },
  { unit: 6, tag: 'relative-parallel', type: 'mc', prompt: 'Going from a major key to its parallel minor adds…', choices: ['3 steps toward the flat side', '1 flat', '3 sharps', 'Nothing — same signature'], answer: '3 steps toward the flat side', explain: 'C (0) → C minor (3♭). D major (2♯) → D minor (1♭): 2♯ → 1♯ → 0 → 1♭ = three steps.' },

  // ---------------- UNIT 7: Key relationships & other scales ----------------
  { unit: 7, tag: 'circle-of-fifths', type: 'mc', prompt: 'Moving clockwise on the circle of fifths…', choices: ['Adds a sharp (or removes a flat)', 'Adds a flat', 'Changes major to minor', 'Moves down a fifth'], answer: 'Adds a sharp (or removes a flat)', explain: 'Clockwise = up a perfect 5th each step: C → G → D …' },
  { unit: 7, tag: 'circle-of-fifths', type: 'mc', prompt: 'Which pair of keys are enharmonic at the bottom of the circle?', choices: ['F♯ major and G♭ major', 'C major and A minor', 'B♭ major and A♯ minor', 'E major and F♭ major'], answer: 'F♯ major and G♭ major', explain: '6 sharps and 6 flats sound the same. (Also B/C♭ and C♯/D♭.)' },
  { unit: 7, tag: 'closely-related', type: 'mc', prompt: 'How many closely related keys does every key have?', choices: ['5', '3', '6', '2'], answer: '5', explain: 'Its relative, plus the keys one step either way on the circle and their relatives.' },
  { unit: 7, tag: 'closely-related', type: 'mc', prompt: 'Closely related keys differ in key signature by…', choices: ['No more than one accidental', 'Exactly two accidentals', 'Three accidentals', 'Only the tonic'], answer: 'No more than one accidental', explain: 'C major\'s closely related keys: A minor, G major, E minor, F major, D minor.' },
  { unit: 7, tag: 'closely-related', type: 'mc', prompt: 'Which key is NOT closely related to C major?', choices: ['C minor', 'A minor', 'G major', 'D minor'], answer: 'C minor', explain: 'C minor has 3 flats — 3 accidentals away. Parallel keys aren\'t closely related.' },
  { unit: 7, tag: 'tonality', type: 'mc', prompt: '"Tonality" means music that…', choices: ['Is organized around a central pitch (the tonic)', 'Uses all 12 pitches equally', 'Has no meter', 'Only uses the pentatonic scale'], answer: 'Is organized around a central pitch (the tonic)', explain: 'Tonal music gravitates toward a home note and key.' },
  { unit: 7, tag: 'pentatonic', type: 'mc', prompt: 'How many notes are in a pentatonic scale?', choices: ['5', '6', '7', '12'], answer: '5', explain: 'Penta = five. The black keys of the piano form one.' },
  { unit: 7, tag: 'pentatonic', type: 'mc', prompt: 'C major pentatonic is…', choices: ['C D E G A', 'C D E F G', 'C E F G B', 'C D F G A'], answer: 'C D E G A', explain: 'Major scale minus degrees 4 and 7 (no half steps).' },
  { unit: 7, tag: 'pentatonic', type: 'mc', prompt: 'Major pentatonic leaves out which major-scale degrees?', choices: ['4 and 7', '3 and 6', '2 and 5', '1 and 4'], answer: '4 and 7', explain: 'Removing 4 and 7 removes both half steps.' },
  { unit: 7, tag: 'chromatic', type: 'mc', prompt: 'How many different pitches are in a chromatic scale?', choices: ['12', '7', '8', '13'], answer: '12', explain: 'Every half step in the octave.' },
  { unit: 7, tag: 'chromatic', type: 'mc', prompt: 'Convention for spelling a chromatic scale is…', choices: ['Sharps going up, flats going down', 'Flats going up, sharps going down', 'Only sharps', 'Only naturals'], answer: 'Sharps going up, flats going down', explain: 'Ascending C C♯ D D♯…; descending C B B♭ A A♭…' },
  { unit: 7, tag: 'modes', type: 'order', prompt: 'Spectrum of modes: order from brightest to darkest.', items: ['Lydian', 'Ionian', 'Mixolydian', 'Dorian', 'Aeolian', 'Phrygian', 'Locrian'], explain: 'Each step darker lowers one more note: Lydian (♯4) → Ionian (major) → Mixolydian (♭7) → Dorian (♭3 ♭7) → Aeolian (natural minor) → Phrygian (♭2) → Locrian (♭2 ♭5).' },
  { unit: 7, tag: 'modes', type: 'mc', prompt: 'Dorian mode is natural minor with a raised…', choices: ['6th', '7th', '2nd', '4th'], answer: '6th', explain: 'D Dorian = D E F G A B C D (white keys from D).' },
  { unit: 7, tag: 'modes', type: 'mc', prompt: 'Lydian mode is major with a raised…', choices: ['4th', '5th', '7th', '2nd'], answer: '4th', explain: 'F Lydian = F G A B C D E F (white keys from F).' },
  { unit: 7, tag: 'modes', type: 'mc', prompt: 'Mixolydian mode is major with a lowered…', choices: ['7th', '3rd', '6th', '2nd'], answer: '7th', explain: 'G Mixolydian = G A B C D E F G (white keys from G).' },
  { unit: 7, tag: 'modes', type: 'mc', prompt: 'Phrygian mode is natural minor with a lowered…', choices: ['2nd', '5th', '7th', '4th'], answer: '2nd', explain: 'E Phrygian = E F G A B C D E (white keys from E).' },
  { unit: 7, tag: 'modes', type: 'mc', prompt: 'Which mode is the same as natural minor?', choices: ['Aeolian', 'Ionian', 'Dorian', 'Locrian'], answer: 'Aeolian', explain: 'A Aeolian = white keys from A = A natural minor. Ionian = major.' },
  { unit: 7, tag: 'modes', type: 'mc', prompt: 'White keys starting on B form which mode?', choices: ['Locrian', 'Lydian', 'Phrygian', 'Mixolydian'], answer: 'Locrian', explain: 'C Ionian, D Dorian, E Phrygian, F Lydian, G Mixolydian, A Aeolian, B Locrian.' },
];
